blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, PostByCategoryView, PostByTagView


app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='post_list'), 
    path('<slug:slug>/', BlogDetailView.as_view(), name='post_detail'),
    path('category/<str:category_name>/', PostByCategoryView.as_view(), name='post_by_category'),
    path('tag/<str:tag_name>/', PostByTagView.as_view(), name='post_by_tag'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('settings.urls', namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('property/', include('property.urls', namespace='property')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('about/', include('about.urls', namespace="about")), 
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home_index'),
    path('search/', views.home_search, name='home_search'),
    path('category/<slug:category>/', views.category_filter, name='category_filter'),
    path('location/<slug:location>/', views.location_filter, name='location_filter'),
    path('contact_us/',views.contact_us, name='contact_us')
]

property/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Property(models.Model):
    owner = models.ForeignKey(User, related_name='property_owner', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='property/')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(max_length=1000)
    location = models.ForeignKey("Location", related_name="property_location", on_delete=models.CASCADE)
    category = models.ForeignKey("Category", related_name="property_category", on_delete=models.CASCADE)
    create_at = models.DateTimeField(default= timezone.now)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)  # Call the real save() method

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse('property:property_detail', kwargs={'slug': self.slug})
    


class PropertyImage(models.Model):
    property= models.ForeignKey("Property", related_name= "property_images", on_delete=models.CASCADE)
    image = models.ImageField(upload_to='property_images/')

    def __str__(self):
        return str(self.property.name)

class Location(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='locations/')

    def __str__(self):
        return str(self.name)

class Category(models.Model):
    name = models.CharField(max_length=40)
    icon = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return str(self.name)
    

class PropertyReview(models.Model):
    property = models.ForeignKey("Property", related_name='review_property', on_delete=models.CASCADE)
    user = models.ForeignKey( User, related_name='review_user', on_delete=models.CASCADE)
    create_at = models.DateTimeField(default=timezone.now)
    rating = models.IntegerField(default=0)
    comment = models.TextField(max_length=500, blank=True, null=True)

    def __str__(self):
        return f"review_{self.user.username}_{self.property.name}"
    

COUNT = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
)
class PropertyBooking(models.Model):
    property = models.ForeignKey("Property", related_name='booking_property', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='booking_user', on_delete=models.CASCADE)
    create_at = models.DateTimeField(default=timezone.now)
    date_from = models.DateField(default=timezone.now)
    date_to = models.DateField(default=timezone.now)
    guest = models.CharField(max_length=2 , choices=COUNT, default='1')
    children = models.CharField(max_length=2, choices=COUNT, default='0')
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    

    def __str__(self):
        return f"booking_{self.user.username}_{self.property.name}"
    

templates/home/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_2.jpg'%});">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
      data-scrollax-parent="true">
      <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
        <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a
              href="{% url 'home:home_index'%}">Home</a></span> <span>Contact</span></p>
        <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Contact Us</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section contact-section ftco-degree-bg">
  <div class="container">
    <div class="row d-flex mb-5 contact-info">
      <div class="col-md-12 mb-4">
        <h2 class="h4">Contact Information</h2>
      </div>
      <div class="w-100"></div>
      <div class="col-md-3">
        <p><span>Address:</span> {{contact.address}}</p>
      </div>
      <div class="col-md-3">
        <p><span>Phone:</span> <a href="tel://{{contact.phone}}">{{contact.phone}}</a></p>
      </div>
      <div class="col-md-3">
        <p><span>Email:</span> <a href="{{contact.email}}">{{contact.email}}</a></p>
      </div>
      <div class="col-md-3">
        <p><span>Website</span> <a href="/">{{contact.site_name}}.com</a></p>
      </div>
    </div>
    <div class="row block-9">
      <div class="col-md-12 pr-md-5">
        <form action="#">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Your Name">
          </div>
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Your Email">
          </div>
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Subject">
          </div>
          <div class="form-group">
            <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
          </div>
          <div class="form-group">
            <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
          </div>
        </form>

      </div>

    </div>
  </div>
</section>
{% endblock content %}

templates/home/home_search.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_5.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
                data-scrollax-parent="true">
                <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                    <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                            class="mr-2"><a href="index.html">Home</a></span> <span>Hotel</span></p>
                    <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Hotels</h1>
                </div>
            </div>
        </div>
    </div>


    <section class="ftco-section ftco-degree-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="row">
                        
                        {% for property in property_list %}
                            
                        <div class="col-md-4 ftco-animate">
                            <div class="destination">
                                <a href="{{property.get_absolute_url}}"
                                    class="img img-2 d-flex justify-content-center align-items-center"
                                    style="background-image: url({{property.image.url}});">
                                    <div class="icon d-flex justify-content-center align-items-center">
                                        <span class="icon-search2"></span>
                                    </div>
                                </a>
                                <div class="text p-3">
                                    <div class="d-flex">
                                        <div class="one">
                                            <h3><a href="{{property.get_absolute_url}}">{{property}}</a></h3>
                                            <p class="rate">
                                                <i class="icon-star"></i>
                                                <i class="icon-star"></i>
                                                <i class="icon-star"></i>
                                                <i class="icon-star"></i>
                                                <i class="icon-star-o"></i>
                                                <span>8 Rating</span>
                                            </p>
                                        </div>
                                        <div class="two">
                                            <span class="price per-price">{{property.price}}<br><small>/night</small></span>
                                        </div>
                                    </div>
                                    <p>{{property.description|truncatewords:3}}</p>
                                    <hr>
                                    <p class="bottom-area d-flex">
                                        <span><i class="icon-map-o"></i> {{property.location}}</span>
                                        <span class="ml-auto"><a href="{{property.get_absolute_url}}">Book Now</a></span>
                                    </p>
                                </div>
                            </div>
                        </div>

                        {% empty %}
                            <p><h5>No properties found.</h5></p>
                        {% endfor %}
                    </div>
                    <!-- Pagination -->
                    {% if is_paginated %}
                    <div class="row mt-5">
                        <div class="col text-center">
                            <div class="block-27">
                                <ul>
                                    
                                    {% if page_obj.has_previous %}
                                        <li><a href="?page={{page_obj.previous_page_number}}">&lt;</a></li>
                                    {% else %}
                                        <li class="disabled"></li>
                                    {% endif %}
                                        

                                    {% for num in paginator.page_range %}
                                        {% if num == page_obj.number %}
                                            <li class="active"><span>{{ num }}</span></li>
                                        {% else %}
                                            <li><a href="?page={{ num }}">{{ num }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                        

                                    {% if page_obj.has_next %}
                                        <li><a href="?page={{page_obj.next_page_number}}">&gt;</a></li>
                                    {% else %}
                                        <li class="disabled"></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div> <!-- .col-md-8 -->
            </div>
        </div>
    </section> <!-- .section -->

{% endblock %}