blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, PostByCategoryView, PostByTagView


app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='post_list'), 
    path('<slug:slug>/', BlogDetailView.as_view(), name='post_detail'),
    path('category/<str:category_name>/', PostByCategoryView.as_view(), name='post_by_category'),
    path('tag/<str:tag_name>/', PostByTagView.as_view(), name='post_by_tag'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('settings.urls', namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('property/', include('property.urls', namespace='property')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('about/', include('about.urls', namespace="about")), 
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home_index'),
    path('search/', views.home_search, name='home_search'),
    path('category/<slug:category>/', views.category_filter, name='category_filter'),
    path('location/<slug:location>/', views.location_filter, name='location_filter'),
    path('contact_us/',views.contact_us, name='contact_us')
]

blog/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils import timezone
from django.utils.text import slugify




class Post(models.Model):
    author = models.ForeignKey(User,related_name='post_author' ,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    tags = TaggableManager()
    image = models.ImageField(upload_to='post_images/')
    created_at = models.DateTimeField(default=timezone.now)
    content = models.TextField(max_length=15000)
    category = models.ForeignKey('Category', related_name='post_category', on_delete=models.CASCADE)
    comments = models.ManyToManyField(User, related_name='post_comments', blank=True)
    slug = models.SlugField(blank=True, null=True)
    
    class Meta:
        ordering = ['-created_at']
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)  # Call the real save() method

    def __str__(self):
        return self.title

    def get_absolute_url(self):

        return reverse('blog:post_detail', kwargs={'slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post, Category
from taggit.models import Tag
from django.db.models import Count, Q

# Create your views here.




class BlogListView(ListView):
    model = Post
    paginate_by = 6 

    def get_queryset(self):
        search = self.request.GET.get('q', '')
        object_list = Post.objects.filter(
            Q(title__icontains = search) |
            Q(content__icontains = search) 
        )
        return object_list






class BlogDetailView(DetailView):
    model = Post


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all().annotate(post_count=Count('post_category'))

        context["tags"] = Tag.objects.all()
        context["recent_posts"] = Post.objects.order_by('-created_at').exclude(id=self.object.id)[:3]
        return context
    

class PostByCategoryView(ListView):
    model = Post
    paginate_by = 6

    def get_queryset(self):
        category_name = self.kwargs['category_name']
        object_list = Post.objects.filter(
            Q(category__name__icontains=category_name)
        )
        return object_list

class PostByTagView(ListView):
    model = Post
    paginate_by = 6

    def get_queryset(self):
        tag_name = self.kwargs['tag_name']
        object_list = Post.objects.filter(
            Q(tags__name__icontains=tag_name)
        )
        return object_list

templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% static '' %}
{% block content %}
<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                        class="mr-2"><a href="{% url 'home:home_index'%}">Home</a></span> <span class="mr-2"><a
                            href="{% url 'blog:post_list'%}">Blog</a></span> <span>Blog Single</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Tips &amp;
                    Articles</h1>
            </div>
        </div>
    </div>
</div>


<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-8 ftco-animate">
                <h2 class="mb-3">{{object.title}}</h2>
                <p>{{post.content|safe}}</p>
                <p>
                    <img src="{{post.image.url}}" alt="" class="img-fluid">
                </p>

                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for tag in post.tags.all %}
                            <a href="#" class="tag-cloud-link">{{tag}}</a>
                        {% endfor %}
                    </div>
                </div>

                <div class="about-author d-flex p-5 bg-light">
                    <div class="bio align-self-md-center mr-5">
                        <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc align-self-md-center">
                        <h3>{{post.author}}</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                            necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente
                            consectetur similique, inventore eos fugit cupiditate numquam!</p>
                    </div>
                </div>


                <div class="pt-5 mt-5">
                    <h3 class="mb-5">Comments</h3>
                    <div id="disqus_thread"></div>
                    <!-- END comment-list -->

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>

                        
                        <form action="#" class="p-5 bg-light">
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <input type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <input type="email" class="form-control" id="email">
                            </div>
                            <div class="form-group">
                                <label for="website">Website</label>
                                <input type="url" class="form-control" id="website">
                            </div>

                            <div class="form-group">
                                <label for="message">Message</label>
                                <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>

                        </form>
                    </div>
                </div>

            </div> <!-- .col-md-8 -->
            <div class="col-md-4 sidebar ftco-animate">
                <div class="sidebar-box">

                    <form action="{% url 'blog:post_list' %}" method="GET" class="search-form">
                        <div class="form-group">
                            <span class="icon fa fa-search"></span>
                            <input type="text" name = "q" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>

                    
                </div>
                <div class="sidebar-box ftco-animate">
                    <div class="categories">
                        <h3>Categories</h3>
                        
                        {% for category in categories %}
                            <li><a href="{% url 'blog:post_by_category' category %}">{{category}} <span>({{category.post_count}})</span></a></li>
                        {% endfor %}
                    </div>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3>Recent Blog</h3>
                    
                    {% for post in recent_posts %}
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4" href= {{post.get_absolute_url}} style="background-image: url({{post.image.url}});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> {{post.created_at|date:'d F Y'}}</a></div>
                                    <div><a href="#"><span class="icon-person"></span> {{post.author}}</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                        
                    

                </div>

                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">
                        
                        {% for tag in tags %}
                            <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag}}</a>
                        {% endfor %}
                            
                        
                    </div>
                </div>
            </div>

        </div>
    </div>
</section> <!-- .section -->


<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    
    var disqus_config = function () {
    this.page.url = window.location.href;  // Use the current page URL instead of hardcoding
    this.page.identifier = "{{post.slug}}"; // This is correct, using the post slug as identifier
    };
    
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://airbnb-18.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

{% endblock %}

templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% static '' %}
{% block content %}

<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            data-scrollax-parent="true">
            <div class="col-md-9 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
                <p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span
                        class="mr-2"><a href="{% url 'home:home_index'%}">Home</a></span> <span>Blog</span></p>
                <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Tips &amp;
                    Articles</h1>
            </div>
        </div>
    </div>
</div>


<section class="ftco-section bg-light">
    <div class="container">
        <div class="row d-flex">
            
            {% for post in object_list %}
                <div class="col-md-3 d-flex ftco-animate">
                    <div class="blog-entry align-self-stretch">
                        <a href="{{post.get_absolute_url}}" class="block-20" style="background-image: url({{post.image.url}});">
                        </a>
                        <div class="text p-4 d-block">
                            <span class="tag">
                                {% if post.tag %}
                                    {{ post.tag }}
                                {% elif post.tags.all %}
                                    {% for tag in post.tags.all %}
                                        {{ tag.name }}{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                {% else %}
                                    No tag
                                {% endif %}
                            </span>
                            <h3 class="heading mt-3"><a href="{{post.get_absolute_url}}">{{post.title}}</a>
                            </h3>
                            <div class="meta mb-3">
                                <div><a href="#">{{post.created_at|date:'d F Y'}}</a></div>
                                <div><a href="#">{{post.author}}</a></div>
                                <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
                


        </div>
            <!-- Pagination -->
            {% if is_paginated %}
            <div class="row mt-5">
                <div class="col text-center">
                    <div class="block-27">
                        <ul>
                            
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{page_obj.previous_page_number}}">&lt;</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                                

                            {% for num in paginator.page_range %}
                                {% if num == page_obj.number %}
                                    <li class="active"><span>{{ num }}</span></li>
                                {% else %}
                                    <li><a href="?page={{ num }}">{{ num }}</a></li>
                                {% endif %}
                            {% endfor %}
                                

                            {% if page_obj.has_next %}
                                <li><a href="?page={{page_obj.next_page_number}}">&gt;</a></li>
                            {% else %}
                                <li class="disabled"></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            {% endif %}
    </div>
</section>
{% endblock %}